// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hello/hello.proto

package go_micro_srv_hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddData) Reset()         { *m = AddData{} }
func (m *AddData) String() string { return proto.CompactTextString(m) }
func (*AddData) ProtoMessage()    {}
func (*AddData) Descriptor() ([]byte, []int) {
	return fileDescriptor_43bcc4e100789d78, []int{0}
}

func (m *AddData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddData.Unmarshal(m, b)
}
func (m *AddData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddData.Marshal(b, m, deterministic)
}
func (m *AddData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddData.Merge(m, src)
}
func (m *AddData) XXX_Size() int {
	return xxx_messageInfo_AddData.Size(m)
}
func (m *AddData) XXX_DiscardUnknown() {
	xxx_messageInfo_AddData.DiscardUnknown(m)
}

var xxx_messageInfo_AddData proto.InternalMessageInfo

func (m *AddData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

//基础response结构
type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*Data  `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_43bcc4e100789d78, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Data struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_43bcc4e100789d78, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddData)(nil), "go.micro.srv.hello.AddData")
	proto.RegisterType((*Response)(nil), "go.micro.srv.hello.Response")
	proto.RegisterType((*Data)(nil), "go.micro.srv.hello.Data")
}

func init() { proto.RegisterFile("proto/hello/hello.proto", fileDescriptor_43bcc4e100789d78) }

var fileDescriptor_43bcc4e100789d78 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0xc5, 0x20,
	0x14, 0xc5, 0xad, 0xd4, 0x56, 0xaf, 0x0e, 0xe6, 0x2e, 0x12, 0x75, 0x68, 0x98, 0x3a, 0x18, 0x4c,
	0xea, 0xe0, 0x5c, 0xe3, 0xe0, 0x8c, 0xbb, 0x09, 0x02, 0xa9, 0x4d, 0x5a, 0x68, 0x80, 0xf4, 0xf3,
	0x1b, 0x78, 0xed, 0xf4, 0xba, 0x90, 0xf3, 0x87, 0x5f, 0x72, 0x00, 0x1e, 0x16, 0xef, 0xa2, 0x7b,
	0xfd, 0x33, 0xd3, 0xb4, 0x9d, 0x3c, 0x27, 0x88, 0x83, 0xe3, 0xf3, 0xa8, 0xbc, 0xe3, 0xc1, 0xaf,
	0x3c, 0x37, 0xec, 0x1d, 0xea, 0x5e, 0xeb, 0x4f, 0x19, 0x25, 0x22, 0x94, 0x56, 0xce, 0x86, 0x16,
	0x4d, 0xd1, 0xde, 0x88, 0xac, 0x91, 0x42, 0xad, 0x9c, 0x8d, 0xc6, 0x46, 0x7a, 0x99, 0xe3, 0xdd,
	0xb2, 0x1f, 0xb8, 0x16, 0x26, 0x2c, 0xce, 0x06, 0x93, 0x48, 0xe5, 0xf4, 0x89, 0xbc, 0x12, 0x59,
	0xe3, 0x3d, 0x90, 0x39, 0x0c, 0x1b, 0x95, 0x24, 0xbe, 0x40, 0xa9, 0x65, 0x94, 0x94, 0x34, 0xa4,
	0xbd, 0xed, 0x28, 0x3f, 0x5f, 0xc3, 0xd3, 0x0e, 0x91, 0x6f, 0xb1, 0x0a, 0xca, 0xe4, 0x3a, 0x01,
	0x77, 0x5f, 0xa9, 0xfb, 0x36, 0x7e, 0x1d, 0x95, 0xc1, 0x0f, 0x20, 0xbd, 0xd6, 0xf8, 0x74, 0x84,
	0x6f, 0x2f, 0x79, 0x7c, 0x3e, 0x2a, 0xf7, 0xb5, 0xec, 0xe2, 0xb7, 0xca, 0xff, 0xf1, 0xf6, 0x1f,
	0x00, 0x00, 0xff, 0xff, 0x91, 0xfa, 0xa6, 0x04, 0x2a, 0x01, 0x00, 0x00,
}
